const Data = [
  {
    id: 1,
    category: "bildung",
    icon: "icon-graduation",
    year: "2023",
    title: "Diplom in Front-End und Back-End Entwicklung",
    desc: "AFPA - Frankreich",
  },
  {
    id: 2,
    category: "bildung",
    icon: "icon-graduation",
    year: "2009-2012",
    title: "Programmierung und Systembetrieb",
    desc: "Gymnasium in Adra",
  },
  {
    id: 3,
    category: "bildung",
    icon: "icon-graduation",
    year: "2005-2008",
    title: "Mittelschulabschluss",
    desc: "College in Adra, Syrien",
  },
  {
    id: 4,
    category: "erfahrung",
    icon: "icon-briefcase",
    year: "2024 - heute",
    title: "Wordpress und frontend Entwickler",
    desc: "Eilinghoff + Team GmbH",
  },
  {
    id: 5,
    category: "erfahrung",
    icon: "icon-briefcase",
    year: "2022",
    title: "Praktikant als WordPress-Entwickler",
    desc: "Foreigners in Europe SRL",
  },
  {
    id: 6,
    category: "erfahrung",
    icon: "icon-briefcase",
    year: "2021",
    title: "Webdesigner & Grafikdesigner",
    desc: "bei Focus Production in der Turkei",
  },
  {
    id: 7,
    category: "erfahrung",
    icon: "icon-briefcase",
    year: "2019",
    title: "Webdesigner & Grafikdesigner",
    desc: "bei Zero  Production in der Turkei",
  },
];

export default Data;
